GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/605d64f27d11331ad029ea6e

###
DELETE http://localhost:3001/api/persons/60107456ead2458987

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Arto Hellas",
    "phone": "85-82344"
}

###
PUT http://localhost:3001/api/persons/6010730fd82e1923509110f3
content-type: application/json

{
    "name": "Anna",
    "phone": "85-82344"
}
