GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/607998

###
DELETE http://localhost:3001/api/persons/60107456ead2458987

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Arto Hellas",
    "number": "85-82344"
}
